//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBkUpUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBkUpUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renews on:.
        /// </summary>
        public static string ABOUTBOX_EXPRIESDATE {
            get {
                return ResourceManager.GetString("ABOUTBOX_EXPRIESDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup destination: {0}.
        /// </summary>
        public static string BOTTOM_TEXT {
            get {
                return ResourceManager.GetString("BOTTOM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now.
        /// </summary>
        public static string BUY_NOW_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("BUY_NOW_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked16 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked20 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked24 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked32 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked40 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked48 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked64 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked80 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked16 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked20 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked24 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked32 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked40 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked48 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked64 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked80 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string DESKTOP {
            get {
                return ResourceManager.GetString("DESKTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select Folder.
        /// </summary>
        public static string DESTINATION_FOLDER_BUTTON {
            get {
                return ResourceManager.GetString("DESTINATION_FOLDER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string DESTINATION_FOLDER_TITLE {
            get {
                return ResourceManager.GetString("DESTINATION_FOLDER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string DISMISS_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("DISMISS_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string DOCUMENTS {
            get {
                return ResourceManager.GetString("DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A backup file named {0} already exists.  What do you want to do?.
        /// </summary>
        public static string DUPLICATE_NAME_VIEW_CONTENT {
            get {
                return ResourceManager.GetString("DUPLICATE_NAME_VIEW_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; backup cannot be deleted..
        /// </summary>
        public static string ERROR_DELETE_FAIL {
            get {
                return ResourceManager.GetString("ERROR_DELETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected backup job has no available backups to restore..
        /// </summary>
        public static string ERROR_JOB_HAS_NO_BACKUPS {
            get {
                return ResourceManager.GetString("ERROR_JOB_HAS_NO_BACKUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty..
        /// </summary>
        public static string ERROR_NAME_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name contains invalid character(s)..
        /// </summary>
        public static string ERROR_NAME_INVALID {
            get {
                return ResourceManager.GetString("ERROR_NAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is too long..
        /// </summary>
        public static string ERROR_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("ERROR_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a backup job..
        /// </summary>
        public static string ERROR_SELECT_A_JOB {
            get {
                return ResourceManager.GetString("ERROR_SELECT_A_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one backup job..
        /// </summary>
        public static string ERROR_SELECT_AT_LEAST_ONE_JOB {
            get {
                return ResourceManager.GetString("ERROR_SELECT_AT_LEAST_ONE_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an available backup..
        /// </summary>
        public static string ERROR_SELECT_ONE_BACKUP {
            get {
                return ResourceManager.GetString("ERROR_SELECT_ONE_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one backup job..
        /// </summary>
        public static string ERROR_SELECT_ONE_JOB {
            get {
                return ResourceManager.GetString("ERROR_SELECT_ONE_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more of the selected backups cannot be deleted..
        /// </summary>
        public static string ERROR_TWO_OR_MORE_DELETE_FAIL {
            get {
                return ResourceManager.GetString("ERROR_TWO_OR_MORE_DELETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string FAVORITES {
            get {
                return ResourceManager.GetString("FAVORITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your grace period has expired..
        /// </summary>
        public static string GRACE_EXPRIED_TITLE {
            get {
                return ResourceManager.GetString("GRACE_EXPRIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days remaining in your grace period:.
        /// </summary>
        public static string GRACE_REMAIN_TITLE {
            get {
                return ResourceManager.GetString("GRACE_REMAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or sign up.
        /// </summary>
        public static string LOG_SIGN_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("LOG_SIGN_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged in as:.
        /// </summary>
        public static string LOGSIGN_SUCESS {
            get {
                return ResourceManager.GetString("LOGSIGN_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Secure Backup.
        /// </summary>
        public static string MODIFY_TITLE {
            get {
                return ResourceManager.GetString("MODIFY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My WinZip Files.
        /// </summary>
        public static string MY_WINZIP_FILES {
            get {
                return ResourceManager.GetString("MY_WINZIP_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string PICTURES {
            get {
                return ResourceManager.GetString("PICTURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected backup job(s)?.
        /// </summary>
        public static string QUESTION_SURE_TO_DELETE_JOBS {
            get {
                return ResourceManager.GetString("QUESTION_SURE_TO_DELETE_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string RESTORE_TEXT {
            get {
                return ResourceManager.GetString("RESTORE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Backup.
        /// </summary>
        public static string SECURE_BACKUP_FRIENDLY_NAME {
            get {
                return ResourceManager.GetString("SECURE_BACKUP_FRIENDLY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the folder to be backed up..
        /// </summary>
        public static string SPECIFY_BACKUP_FOLDER {
            get {
                return ResourceManager.GetString("SPECIFY_BACKUP_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an encryption password and method..
        /// </summary>
        public static string SPECIFY_ENCRYPTION_METHOD {
            get {
                return ResourceManager.GetString("SPECIFY_ENCRYPTION_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify where backups should be stored..
        /// </summary>
        public static string SPECIFY_STORE_FOLDER {
            get {
                return ResourceManager.GetString("SPECIFY_STORE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for subscribing!.
        /// </summary>
        public static string SUBSCRIBE_SUCESS {
            get {
                return ResourceManager.GetString("SUBSCRIBE_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinZip Secure Backup - {0}.
        /// </summary>
        public static string TASK_SCHEDULER_PRE {
            get {
                return ResourceManager.GetString("TASK_SCHEDULER_PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has expired.
        /// </summary>
        public static string TRIAL_EXPRIED_CONTENT {
            get {
                return ResourceManager.GetString("TRIAL_EXPRIED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your WinZip trial has expired..
        /// </summary>
        public static string TRIAL_EXPRIED_TITLE {
            get {
                return ResourceManager.GetString("TRIAL_EXPRIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string TRIAL_REMAIN_DAYS {
            get {
                return ResourceManager.GetString("TRIAL_REMAIN_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days remaining in your free trial:.
        /// </summary>
        public static string TRIAL_REMAIN_TITLE {
            get {
                return ResourceManager.GetString("TRIAL_REMAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to {0} is denied..
        /// </summary>
        public static string WARNING_ACCESS_DENY {
            get {
                return ResourceManager.GetString("WARNING_ACCESS_DENY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitations in cloud services prevent checking the root folder of the cloud service. Instead, please check the files and folders it contains..
        /// </summary>
        public static string WARNING_LIMITATIONS_CLOUD_ROOT {
            get {
                return ResourceManager.GetString("WARNING_LIMITATIONS_CLOUD_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your administrator has restricted the use of this feature..
        /// </summary>
        public static string WARNING_RESTRICTED_FEATURE {
            get {
                return ResourceManager.GetString("WARNING_RESTRICTED_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinZip.
        /// </summary>
        public static string WINZIP {
            get {
                return ResourceManager.GetString("WINZIP", resourceCulture);
            }
        }
    }
}
