//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImgUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renews on:.
        /// </summary>
        internal static string ABOUTBOX_EXPRIESDATE {
            get {
                return ResourceManager.GetString("ABOUTBOX_EXPRIESDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the options dialog.
        /// </summary>
        internal static string ADMIN_REQUIRED_DLG_CANCEL_TIP {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED_DLG_CANCEL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to set one or more of the options you have changed, administrator privileges are required..
        /// </summary>
        internal static string ADMIN_REQUIRED_DLG_CONTENT {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED_DLG_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string ADMIN_REQUIRED_DLG_OK {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED_DLG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click &apos;Yes&apos; or &apos;OK&apos; if Windows asks for permission to make changes.
        /// </summary>
        internal static string ADMIN_REQUIRED_DLG_OK_TIP {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED_DLG_OK_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges required.
        /// </summary>
        internal static string ADMIN_REQUIRED_DLG_TITLE {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED_DLG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now.
        /// </summary>
        internal static string BUY_NOW_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("BUY_NOW_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked16 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked20 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked24 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked32 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked40 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked48 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked64 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked80 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked16 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked20 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked24 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked32 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked40 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked48 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked64 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked80 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0} files....
        /// </summary>
        internal static string COPYING_N_FILES {
            get {
                return ResourceManager.GetString("COPYING_N_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create from Image File.
        /// </summary>
        internal static string CREATE_FROM_IMAGE_FILE {
            get {
                return ResourceManager.GetString("CREATE_FROM_IMAGE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create.
        /// </summary>
        internal static string CREATE_FROM_PICKER_BUTTON {
            get {
                return ResourceManager.GetString("CREATE_FROM_PICKER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.png.
        /// </summary>
        internal static string DEFAULT_NEW_IMAGE_NAME {
            get {
                return ResourceManager.GetString("DEFAULT_NEW_IMAGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string DISMISS_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("DISMISS_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform this action on this type of file..
        /// </summary>
        internal static string ERROR_ACTION_NOT_SUPPORT {
            get {
                return ResourceManager.GetString("ERROR_ACTION_NOT_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No opened image. Please open an image file..
        /// </summary>
        internal static string ERROR_NO_OPENED_IMAGE {
            get {
                return ResourceManager.GetString("ERROR_NO_OPENED_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save to Zip. WinZip Image Manager was not run from WinZip&apos;s Files Pane or Zip Pane..
        /// </summary>
        internal static string EXECUTE_SAVE_TO_ZIP_INDEPENDENTLY_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_SAVE_TO_ZIP_INDEPENDENTLY_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon EyeballDisable {
            get {
                object obj = ResourceManager.GetObject("EyeballDisable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon EyeballEnable {
            get {
                object obj = ResourceManager.GetObject("EyeballEnable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &apos;Change&apos; to select the default handler.
        /// </summary>
        internal static string FILE_ASSOC_HANDLER_FILE_NAME {
            get {
                return ResourceManager.GetString("FILE_ASSOC_HANDLER_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose WinZip Image Manager and click &apos;OK&apos;.
        /// </summary>
        internal static string FILE_ASSOC_HTML_CHOOSE_TIP {
            get {
                return ResourceManager.GetString("FILE_ASSOC_HTML_CHOOSE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Change&apos;.
        /// </summary>
        internal static string FILE_ASSOC_HTML_CLICK_TIP {
            get {
                return ResourceManager.GetString("FILE_ASSOC_HTML_CLICK_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the File Properties dialog again.
        /// </summary>
        internal static string FILE_ASSOC_HTML_REDISPLAY_TEXT {
            get {
                return ResourceManager.GetString("FILE_ASSOC_HTML_REDISPLAY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set WinZip Image Manager as the default app in three clicks.
        /// </summary>
        internal static string FILE_ASSOC_HTML_TITLE {
            get {
                return ResourceManager.GetString("FILE_ASSOC_HTML_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP files|*.bmp|PNG files|*.png|GIF files|*.gif|JPG files|*.jpg|JP2 files|*.jp2|PSD files|*.psd|TIF files|*.tif|WEBP files|*.webp|SVG files|*.svg|Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string FILE_FORMAT_BMP {
            get {
                return ResourceManager.GetString("FILE_FORMAT_BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF files|*.gif|BMP files|*.bmp|PNG files|*.png|JPG files|*.jpg|JP2 files|*.jp2|PSD files|*.psd|TIF files|*.tif|WEBP files|*.webp|SVG files|*.svg|Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string FILE_FORMAT_GIF {
            get {
                return ResourceManager.GetString("FILE_FORMAT_GIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPG files|*.jpg|BMP files|*.bmp|PNG files|*.png|GIF files|*.gif|JP2 files|*.jp2|PSD files|*.psd|TIF files|*.tif|WEBP files|*.webp|SVG files|*.svg|Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string FILE_FORMAT_JPEG {
            get {
                return ResourceManager.GetString("FILE_FORMAT_JPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP2 files|*.jp2|BMP files|*.bmp|PNG files|*.png|GIF files|*.gif|JPG files|*.jpg|PSD files|*.psd|TIF files|*.tif|WEBP files|*.webp|SVG files|*.svg|Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string FILE_FORMAT_JPG2000 {
            get {
                return ResourceManager.GetString("FILE_FORMAT_JPG2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG files|*.png|BMP files|*.bmp|GIF files|*.gif|JPG files|*.jpg|JP2 files|*.jp2|PSD files|*.psd|TIF files|*.tif|WEBP files|*.webp|SVG files|*.svg|Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string FILE_FORMAT_PNG {
            get {
                return ResourceManager.GetString("FILE_FORMAT_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSD files|*.psd|BMP files|*.bmp|PNG files|*.png|GIF files|*.gif|JPG files|*.jpg|JP2 files|*.jp2|TIF files|*.tif|WEBP files|*.webp|SVG files|*.svg|Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string FILE_FORMAT_PSD {
            get {
                return ResourceManager.GetString("FILE_FORMAT_PSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVG files|*.svg|BMP files|*.bmp|PNG files|*.png|GIF files|*.gif|JPG files|*.jpg|JP2 files|*.jp2|PSD files|*.psd|TIF files|*.tif|WEBP files|*.webp|Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string FILE_FORMAT_SVG {
            get {
                return ResourceManager.GetString("FILE_FORMAT_SVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIF files|*.tif|BMP files|*.bmp|PNG files|*.png|GIF files|*.gif|JPG files|*.jpg|JP2 files|*.jp2|PSD files|*.psd|WEBP files|*.webp|SVG files|*.svg|Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string FILE_FORMAT_TIF {
            get {
                return ResourceManager.GetString("FILE_FORMAT_TIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEBP files|*.webp|BMP files|*.bmp|PNG files|*.png|GIF files|*.gif|JPG files|*.jpg|JP2 files|*.jp2|PSD files|*.psd|TIF files|*.tif|SVG files|*.svg|Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string FILE_FORMAT_WEBP {
            get {
                return ResourceManager.GetString("FILE_FORMAT_WEBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed. The file is in use. Please try again later..
        /// </summary>
        internal static string FILE_IN_USE_WARNING {
            get {
                return ResourceManager.GetString("FILE_IN_USE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open &apos;{0}&apos; - the file has been deleted or moved..
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your grace period has expired..
        /// </summary>
        internal static string GRACE_EXPRIED_TITLE {
            get {
                return ResourceManager.GetString("GRACE_EXPRIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days remaining in your grace period:.
        /// </summary>
        internal static string GRACE_REMAIN_TITLE {
            get {
                return ResourceManager.GetString("GRACE_REMAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string IDENTIFYKEY_OK {
            get {
                return ResourceManager.GetString("IDENTIFYKEY_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is read-only and cannot be updated..
        /// </summary>
        internal static string IMAGE_FILENAME_IS_READ_ONLY {
            get {
                return ResourceManager.GetString("IMAGE_FILENAME_IS_READ_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This image is read-only and cannot be updated..
        /// </summary>
        internal static string IMAGE_IS_READ_ONLY {
            get {
                return ResourceManager.GetString("IMAGE_IS_READ_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Manager.
        /// </summary>
        internal static string IMAGE_UTILITY_FRIENDLY_NAME {
            get {
                return ResourceManager.GetString("IMAGE_UTILITY_FRIENDLY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinZip Image Manager.
        /// </summary>
        internal static string IMAGE_UTILITY_TITLE {
            get {
                return ResourceManager.GetString("IMAGE_UTILITY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ImgUtil {
            get {
                object obj = ResourceManager.GetObject("ImgUtil", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string IMPORT {
            get {
                return ResourceManager.GetString("IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Image.
        /// </summary>
        internal static string IMPORT_IMAGE {
            get {
                return ResourceManager.GetString("IMPORT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual size.
        /// </summary>
        internal static string INFO_VIEW_BY_ACTUAL_SIZE {
            get {
                return ResourceManager.GetString("INFO_VIEW_BY_ACTUAL_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size to fit.
        /// </summary>
        internal static string INFO_VIEW_BY_SIZE_TO_FIT {
            get {
                return ResourceManager.GetString("INFO_VIEW_BY_SIZE_TO_FIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop and Start menu shortcuts and File Associations have been disabled by your system administrator..
        /// </summary>
        internal static string INTEGRATION_DISABLE_BY_ADMIN {
            get {
                return ResourceManager.GetString("INTEGRATION_DISABLE_BY_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or sign up.
        /// </summary>
        internal static string LOG_SIGN_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("LOG_SIGN_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged in as:.
        /// </summary>
        internal static string LOGSIGN_SUCESS {
            get {
                return ResourceManager.GetString("LOGSIGN_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NEW_NAME {
            get {
                return ResourceManager.GetString("NEW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string OPEN_PICKER_BUTTON {
            get {
                return ResourceManager.GetString("OPEN_PICKER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.bmp;*.dib;*.gif;*.jpg;*.jpeg;*.jfif;*.jp2;*.png;*.psd;*.tif;*.tiff;*.webp;*.svg.
        /// </summary>
        internal static string OPEN_PICKER_FILTER {
            get {
                return ResourceManager.GetString("OPEN_PICKER_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotating {0} file(s)....
        /// </summary>
        internal static string ROTATING_N_FILES {
            get {
                return ResourceManager.GetString("ROTATING_N_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SAVE_AS {
            get {
                return ResourceManager.GetString("SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to PC or Cloud.
        /// </summary>
        internal static string SAVE_TO_PC_OR_CLOUD {
            get {
                return ResourceManager.GetString("SAVE_TO_PC_OR_CLOUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share selected files.
        /// </summary>
        internal static string SHARE_CHARMS_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHARE_CHARMS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for subscribing!.
        /// </summary>
        internal static string SUBSCRIBE_SUCESS {
            get {
                return ResourceManager.GetString("SUBSCRIBE_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!  WinZip Image Manager is your default photo viewer app.
        /// </summary>
        internal static string SUP_ALREADY_DEFAULT_APP_TEXT {
            get {
                return ResourceManager.GetString("SUP_ALREADY_DEFAULT_APP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make WinZip Image Manager your default app.
        /// </summary>
        internal static string SUP_MAKE_DEFAULT_APP_TEXT {
            get {
                return ResourceManager.GetString("SUP_MAKE_DEFAULT_APP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes that you have made?.
        /// </summary>
        internal static string TASKDLG_ASK_TO_SAVE_TITLE {
            get {
                return ResourceManager.GetString("TASKDLG_ASK_TO_SAVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TASKDLG_CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("TASKDLG_CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the image&apos;s file extension.
        /// </summary>
        internal static string TASKDLG_CHANGE_EXT_BUTTON {
            get {
                return ResourceManager.GetString("TASKDLG_CHANGE_EXT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change it to the correct file extension corresponding to its format..
        /// </summary>
        internal static string TASKDLG_CHANGE_EXT_BUTTON_TIP {
            get {
                return ResourceManager.GetString("TASKDLG_CHANGE_EXT_BUTTON_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the image to the correct format?.
        /// </summary>
        internal static string TASKDLG_CHANGE_EXT_TITLE {
            get {
                return ResourceManager.GetString("TASKDLG_CHANGE_EXT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this for all files.
        /// </summary>
        internal static string TASKDLG_DO_FOR_ALL_FILE {
            get {
                return ResourceManager.GetString("TASKDLG_DO_FOR_ALL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t change it, just open it.
        /// </summary>
        internal static string TASKDLG_DONT_CHANGE_BUTTON {
            get {
                return ResourceManager.GetString("TASKDLG_DONT_CHANGE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image is opened, but some operations will be disabled..
        /// </summary>
        internal static string TASKDLG_DONT_CHANGE_BUTTON_TIP {
            get {
                return ResourceManager.GetString("TASKDLG_DONT_CHANGE_BUTTON_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Save.
        /// </summary>
        internal static string TASKDLG_DONT_SAVE_BUTTON {
            get {
                return ResourceManager.GetString("TASKDLG_DONT_SAVE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes will be lost..
        /// </summary>
        internal static string TASKDLG_DONT_SAVE_BUTTON_TIP {
            get {
                return ResourceManager.GetString("TASKDLG_DONT_SAVE_BUTTON_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current image has been modified. What do you want to do?.
        /// </summary>
        internal static string TASKDLG_IMAGE_MODIFIED {
            get {
                return ResourceManager.GetString("TASKDLG_IMAGE_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with....
        /// </summary>
        internal static string TASKDLG_OPENWITH_BUTTON {
            get {
                return ResourceManager.GetString("TASKDLG_OPENWITH_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore your changes, then open the original image with another application.
        /// </summary>
        internal static string TASKDLG_OPENWITH_BUTTON_TIP {
            get {
                return ResourceManager.GetString("TASKDLG_OPENWITH_BUTTON_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string TASKDLG_SAVE_AS_BUTTON {
            get {
                return ResourceManager.GetString("TASKDLG_SAVE_AS_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your changes to another location, filename or image type..
        /// </summary>
        internal static string TASKDLG_SAVE_AS_BUTTON_TIP {
            get {
                return ResourceManager.GetString("TASKDLG_SAVE_AS_BUTTON_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TASKDLG_SAVE_BUTTON {
            get {
                return ResourceManager.GetString("TASKDLG_SAVE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your changes to the current image file..
        /// </summary>
        internal static string TASKDLG_SAVE_BUTTON_TIP {
            get {
                return ResourceManager.GetString("TASKDLG_SAVE_BUTTON_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Open with....
        /// </summary>
        internal static string TASKDLG_SAVE_OPENWITH_BUTTON {
            get {
                return ResourceManager.GetString("TASKDLG_SAVE_OPENWITH_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your changes, then open the current image with another application.
        /// </summary>
        internal static string TASKDLG_SAVE_OPENWITH_BUTTON_TIP {
            get {
                return ResourceManager.GetString("TASKDLG_SAVE_OPENWITH_BUTTON_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the options below..
        /// </summary>
        internal static string TASKDLG_SELECT_ONE {
            get {
                return ResourceManager.GetString("TASKDLG_SELECT_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current image file has been modified. To continue, select one of the options below..
        /// </summary>
        internal static string TASKDLG_SELECT_ONE_MODIFIED {
            get {
                return ResourceManager.GetString("TASKDLG_SELECT_ONE_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this file.
        /// </summary>
        internal static string TASKDLG_SKIP_BUTTON {
            get {
                return ResourceManager.GetString("TASKDLG_SKIP_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file will be excluded from this operation..
        /// </summary>
        internal static string TASKDLG_SKIP_BUTTON_CONTENT {
            get {
                return ResourceManager.GetString("TASKDLG_SKIP_BUTTON_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file extension does not match image content..
        /// </summary>
        internal static string TASKDLG_WRONG_EXT_TITLE {
            get {
                return ResourceManager.GetString("TASKDLG_WRONG_EXT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current image is actually in &quot;{0}&quot; format but has a &quot;{1}&quot; file extension.  To continue, use one of the options below..
        /// </summary>
        internal static string TASKDLG_WRONG_EXTENSION {
            get {
                return ResourceManager.GetString("TASKDLG_WRONG_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current image is actually in &quot;{0}&quot; format but has a &quot;{1}&quot; file extension.  However, the file cannot be renamed..
        /// </summary>
        internal static string TASKDLG_WRONG_EXTENSION_CANNOT_RENAMED {
            get {
                return ResourceManager.GetString("TASKDLG_WRONG_EXTENSION_CANNOT_RENAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image has been added to the Teams Backgrounds folder..
        /// </summary>
        internal static string TEXT_ADD_TO_TEAMS_BG_SUCCESS {
            get {
                return ResourceManager.GetString("TEXT_ADD_TO_TEAMS_BG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images have been added to the Teams Background folder..
        /// </summary>
        internal static string TEXT_ADD_TO_TEAMS_BG_SUCCESS_MULTI {
            get {
                return ResourceManager.GetString("TEXT_ADD_TO_TEAMS_BG_SUCCESS_MULTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to set this image as your desktop background?.
        /// </summary>
        internal static string TEXT_CONFIRM_SET_DESKTOP_BG {
            get {
                return ResourceManager.GetString("TEXT_CONFIRM_SET_DESKTOP_BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion completed successfully..
        /// </summary>
        internal static string TEXT_CONVERSION_SUCCESS {
            get {
                return ResourceManager.GetString("TEXT_CONVERSION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} already exists. Do you want to replace it?.
        /// </summary>
        internal static string TEXT_EXIST_AND_REPLACE {
            get {
                return ResourceManager.GetString("TEXT_EXIST_AND_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string TEXT_HEIGHT {
            get {
                return ResourceManager.GetString("TEXT_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected image(s) rotated 90 degrees clockwise..
        /// </summary>
        internal static string TEXT_ROTATE_CLOCKWISE {
            get {
                return ResourceManager.GetString("TEXT_ROTATE_CLOCKWISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected image(s) rotated 90 degrees counterclockwise..
        /// </summary>
        internal static string TEXT_ROTATE_COUNTER_CLOCKWISE {
            get {
                return ResourceManager.GetString("TEXT_ROTATE_COUNTER_CLOCKWISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string TEXT_WIDTH {
            get {
                return ResourceManager.GetString("TEXT_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has expired.
        /// </summary>
        internal static string TRIAL_EXPRIED_CONTENT {
            get {
                return ResourceManager.GetString("TRIAL_EXPRIED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your WinZip trial has expired..
        /// </summary>
        internal static string TRIAL_EXPRIED_TITLE {
            get {
                return ResourceManager.GetString("TRIAL_EXPRIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TRIAL_REMAIN_DAYS {
            get {
                return ResourceManager.GetString("TRIAL_REMAIN_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days remaining in your free trial:.
        /// </summary>
        internal static string TRIAL_REMAIN_TITLE {
            get {
                return ResourceManager.GetString("TRIAL_REMAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied..
        /// </summary>
        internal static string WARNING_ACCESS_DENY {
            get {
                return ResourceManager.GetString("WARNING_ACCESS_DENY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image dimension(s) specified (width={0}, height={1}).
        /// </summary>
        internal static string WARNING_BAD_IMAGE_DIMENSION {
            get {
                return ResourceManager.GetString("WARNING_BAD_IMAGE_DIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password cannot be empty. Please enter the password..
        /// </summary>
        internal static string WARNING_ENCRYPT_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("WARNING_ENCRYPT_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords you typed do not match. Please enter the password again..
        /// </summary>
        internal static string WARNING_ENCRYPT_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("WARNING_ENCRYPT_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file &apos;{0}&apos;. It does not appear to be a valid Image file..
        /// </summary>
        internal static string WARNING_INVALID_FILE {
            get {
                return ResourceManager.GetString("WARNING_INVALID_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path, file name, or both are too long..
        /// </summary>
        internal static string WARNING_PATH_TOO_LONG {
            get {
                return ResourceManager.GetString("WARNING_PATH_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your administrator has restricted the use of this feature..
        /// </summary>
        internal static string WARNING_RESTRICTED_FEATURE {
            get {
                return ResourceManager.GetString("WARNING_RESTRICTED_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t save here. Please choose another location..
        /// </summary>
        internal static string WARNING_SAVE_LOCATION_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("WARNING_SAVE_LOCATION_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file &apos;{0}&apos;. It is not an image file supported by WinZip Image Manager..
        /// </summary>
        internal static string WARNING_UNSUPPORTED_FILE {
            get {
                return ResourceManager.GetString("WARNING_UNSUPPORTED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinZip.
        /// </summary>
        internal static string WINZIP {
            get {
                return ResourceManager.GetString("WINZIP", resourceCulture);
            }
        }
    }
}
