//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renews on:.
        /// </summary>
        internal static string ABOUTBOX_EXPRIESDATE {
            get {
                return ResourceManager.GetString("ABOUTBOX_EXPRIESDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Bookmark.
        /// </summary>
        internal static string ADD_BOOKMARK_TITLE {
            get {
                return ResourceManager.GetString("ADD_BOOKMARK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a sub-bookmark.
        /// </summary>
        internal static string ADD_SUBBOOKMARK_TITLE {
            get {
                return ResourceManager.GetString("ADD_SUBBOOKMARK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ADMIN_REQUIRED_DLG_CANCEL {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED_DLG_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the options dialog.
        /// </summary>
        internal static string ADMIN_REQUIRED_DLG_CANCEL_TIP {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED_DLG_CANCEL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to set one or more of the options you have changed, administrator privileges are required..
        /// </summary>
        internal static string ADMIN_REQUIRED_DLG_CONTENT {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED_DLG_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string ADMIN_REQUIRED_DLG_OK {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED_DLG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click &apos;Yes&apos; or &apos;OK&apos; if Windows asks for permission to make changes.
        /// </summary>
        internal static string ADMIN_REQUIRED_DLG_OK_TIP {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED_DLG_OK_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges required.
        /// </summary>
        internal static string ADMIN_REQUIRED_DLG_TITLE {
            get {
                return ResourceManager.GetString("ADMIN_REQUIRED_DLG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave this PDF locked with the existing permissions.
        /// </summary>
        internal static string BUTTON_CANCEL_PERMISSION_CHANGE_TIP {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL_PERMISSION_CHANGE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change passwords and/or permissions.
        /// </summary>
        internal static string BUTTON_CHANGE_PERMISSIONS {
            get {
                return ResourceManager.GetString("BUTTON_CHANGE_PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change access passwords and/or change what a user can do to this locked PDF.
        /// </summary>
        internal static string BUTTON_CHANGE_PERMISSIONS_TIP {
            get {
                return ResourceManager.GetString("BUTTON_CHANGE_PERMISSIONS_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this file.
        /// </summary>
        internal static string BUTTON_SKIP {
            get {
                return ResourceManager.GetString("BUTTON_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        internal static string BUY_NOW_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("BUY_NOW_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked16 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked20 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked24 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked32 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked40 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked48 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked64 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxChecked80 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked16 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked20 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked24 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked32 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked40 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked48 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked64 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckBoxUnchecked80 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca&amp;ncel.
        /// </summary>
        internal static string COLOR_DIALOG_CANCEL {
            get {
                return ResourceManager.GetString("COLOR_DIALOG_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&amp;K.
        /// </summary>
        internal static string COLOR_DIALOG_OK {
            get {
                return ResourceManager.GetString("COLOR_DIALOG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re&amp;move background color.
        /// </summary>
        internal static string COLOR_DIALOG_REMOVEBACKGROUNDCOLOR {
            get {
                return ResourceManager.GetString("COLOR_DIALOG_REMOVEBACKGROUNDCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se&amp;t background color.
        /// </summary>
        internal static string COLOR_DIALOG_SETBACKGROUNDCOLOR {
            get {
                return ResourceManager.GetString("COLOR_DIALOG_SETBACKGROUNDCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |Solid.
        /// </summary>
        internal static string COLOR_DIALOG_SOLID {
            get {
                return ResourceManager.GetString("COLOR_DIALOG_SOLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding....
        /// </summary>
        internal static string COMMENT_ADDING_TEXT {
            get {
                return ResourceManager.GetString("COMMENT_ADDING_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Comment.
        /// </summary>
        internal static string COMMENT_DIALOG_ADDCOMMENT {
            get {
                return ResourceManager.GetString("COMMENT_DIALOG_ADDCOMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Comment.
        /// </summary>
        internal static string COMMENT_DIALOG_EDITCOMMENT {
            get {
                return ResourceManager.GetString("COMMENT_DIALOG_EDITCOMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Empty).
        /// </summary>
        internal static string COMMENT_EMPTY_CONTENT {
            get {
                return ResourceManager.GetString("COMMENT_EMPTY_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}.
        /// </summary>
        internal static string COMMENT_PAGE_TITLE {
            get {
                return ResourceManager.GetString("COMMENT_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments ({0}).
        /// </summary>
        internal static string COMMENT_PANE_TITLE {
            get {
                return ResourceManager.GetString("COMMENT_PANE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string COMMENT_SORT_AUTHOR {
            get {
                return ResourceManager.GetString("COMMENT_SORT_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string COMMENT_SORT_DATE {
            get {
                return ResourceManager.GetString("COMMENT_SORT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string COMMENT_SORT_PAGE {
            get {
                return ResourceManager.GetString("COMMENT_SORT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this file.
        /// </summary>
        internal static string CONFIRM_DIALOG_BUTTON_NO_TEXT {
            get {
                return ResourceManager.GetString("CONFIRM_DIALOG_BUTTON_NO_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy, but keep both files.
        /// </summary>
        internal static string CONFIRM_DIALOG_BUTTON_OK_TEXT {
            get {
                return ResourceManager.GetString("CONFIRM_DIALOG_BUTTON_OK_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the file in the destination folder.
        /// </summary>
        internal static string CONFIRM_DIALOG_BUTTON_YES_TEXT {
            get {
                return ResourceManager.GetString("CONFIRM_DIALOG_BUTTON_YES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to replace the existing file:
        ///        {0}
        ///
        ///with this one:
        ///        {1}.
        /// </summary>
        internal static string CONFIRM_DIALOG_CONTENT {
            get {
                return ResourceManager.GetString("CONFIRM_DIALOG_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder already contains this file..
        /// </summary>
        internal static string CONFIRM_DIALOG_MAIN_INSTRUCTION {
            get {
                return ResourceManager.GetString("CONFIRM_DIALOG_MAIN_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm File Replace.
        /// </summary>
        internal static string CONFIRM_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this for all affected files.
        /// </summary>
        internal static string CONFIRM_DIALOG_VERIFICATION_TEXT {
            get {
                return ResourceManager.GetString("CONFIRM_DIALOG_VERIFICATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion completed successfully..
        /// </summary>
        internal static string CONVERSION_COMPLETED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("CONVERSION_COMPLETED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting {0} file(s)....
        /// </summary>
        internal static string CONVERTING_FILES {
            get {
                return ResourceManager.GetString("CONVERTING_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Documents|*.pdf*;*.doc*;*.xls*;*.ppt*;*.htm*;*.tex;*.txt*;*.rtf*;*.xps;*.bmp*;*.ccitt;*.dib;*.emf;*.exif*;*.gif;*.ico;*.jp*g;*.jfif;*.png;*.tif*;*.wmf|PDF files|*.pdf|Documents|*.doc*;*.xls*;*.ppt*;*.htm;*.tex;*.txt;*.rtf;*.xps|Images|*.bmp;*.ccitt;*.dib;*.emf;*.exif*;*.gif;*.ico;*.jp*g;*.jfif;*.png;*.tif*;*.wmf.
        /// </summary>
        internal static string CREATE_FROM_FILTERS {
            get {
                return ResourceManager.GetString("CREATE_FROM_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create from Files.
        /// </summary>
        internal static string CREATE_FROM_PICKER_TITLE {
            get {
                return ResourceManager.GetString("CREATE_FROM_PICKER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.pdf.
        /// </summary>
        internal static string DEFAULT_PDF_TITLE_NAME {
            get {
                return ResourceManager.GetString("DEFAULT_PDF_TITLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all blank pages?.
        /// </summary>
        internal static string DELETE_BLANK_PAGES_CONFIRMING {
            get {
                return ResourceManager.GetString("DELETE_BLANK_PAGES_CONFIRMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank page(s) deleted..
        /// </summary>
        internal static string DELETE_BLANK_PAGES_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("DELETE_BLANK_PAGES_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected page(s)?.
        /// </summary>
        internal static string DELETE_PAGES_CONFIRMING {
            get {
                return ResourceManager.GetString("DELETE_PAGES_CONFIRMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected pages(s) have been deleted..
        /// </summary>
        internal static string DELETE_PAGES_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("DELETE_PAGES_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string DISMISS_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("DISMISS_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image you selected is invalid. Please select another image..
        /// </summary>
        internal static string ERROR_IMAGE_INVALID {
            get {
                return ResourceManager.GetString("ERROR_IMAGE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a bookmark..
        /// </summary>
        internal static string EXECUTE_ADD_SUB_BOOKMARK_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_ADD_SUB_BOOKMARK_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to close. No opened PDF. Please import pages or open a PDF..
        /// </summary>
        internal static string EXECUTE_CLOSE_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_CLOSE_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images to extract. No opened PDF. Please import pages or open a PDF..
        /// </summary>
        internal static string EXECUTE_EXTRACT_IMAGES_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_EXTRACT_IMAGES_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pages to extract. No opened PDF. Please import pages or open a PDF..
        /// </summary>
        internal static string EXECUTE_EXTRACT_PAGES_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_EXTRACT_PAGES_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a bookmark..
        /// </summary>
        internal static string EXECUTE_GOTO_BOOKMARK_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_GOTO_BOOKMARK_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a bookmark..
        /// </summary>
        internal static string EXECUTE_REMOVE_BOOKMARK_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_REMOVE_BOOKMARK_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a bookmark..
        /// </summary>
        internal static string EXECUTE_RENAME_BOOKMARK_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_RENAME_BOOKMARK_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the page(s) to rotate..
        /// </summary>
        internal static string EXECUTE_ROTATE_PAGES_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_ROTATE_PAGES_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save to Zip. WinZip PDF Express was not run from WinZip&apos;s Files Pane or Zip Pane..
        /// </summary>
        internal static string EXECUTE_SAVE_TO_ZIP_INDEPENDENTLY_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_SAVE_TO_ZIP_INDEPENDENTLY_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the page to use to set the background color..
        /// </summary>
        internal static string EXECUTE_SET_BACKGROUND_COLOR_PDF_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_SET_BACKGROUND_COLOR_PDF_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the page(s) to watermark..
        /// </summary>
        internal static string EXECUTE_WATERMARK_PAGES_TIPS {
            get {
                return ResourceManager.GetString("EXECUTE_WATERMARK_PAGES_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting image(s) from {0}….
        /// </summary>
        internal static string EXTRACT_IMAGE_PROGRESS_TEXT_CONTENT {
            get {
                return ResourceManager.GetString("EXTRACT_IMAGE_PROGRESS_TEXT_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting page(s) from {0}….
        /// </summary>
        internal static string EXTRACT_PAGE_PROGRESS_TEXT_CONTENT {
            get {
                return ResourceManager.GetString("EXTRACT_PAGE_PROGRESS_TEXT_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon EyeballDisable {
            get {
                object obj = ResourceManager.GetObject("EyeballDisable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon EyeballEnable {
            get {
                object obj = ResourceManager.GetObject("EyeballEnable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &apos;Change&apos; to select the default handler.
        /// </summary>
        internal static string FILE_ASSOC_HANDLER_FILE_NAME {
            get {
                return ResourceManager.GetString("FILE_ASSOC_HANDLER_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose WinZip PDF Express and click &apos;OK&apos;.
        /// </summary>
        internal static string FILE_ASSOC_HTML_CHOOSE_TIP {
            get {
                return ResourceManager.GetString("FILE_ASSOC_HTML_CHOOSE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Change&apos;.
        /// </summary>
        internal static string FILE_ASSOC_HTML_CLICK_TIP {
            get {
                return ResourceManager.GetString("FILE_ASSOC_HTML_CLICK_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the File Properties dialog again.
        /// </summary>
        internal static string FILE_ASSOC_HTML_REDISPLAY_TEXT {
            get {
                return ResourceManager.GetString("FILE_ASSOC_HTML_REDISPLAY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set WinZip PDF Express as the default app in three clicks.
        /// </summary>
        internal static string FILE_ASSOC_HTML_TITLE {
            get {
                return ResourceManager.GetString("FILE_ASSOC_HTML_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed. The file is in use. Please try again later..
        /// </summary>
        internal static string FILE_IN_USE_WARNING {
            get {
                return ResourceManager.GetString("FILE_IN_USE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open &apos;{0}&apos; - the file has been deleted or moved..
        /// </summary>
        internal static string FILE_NOT_FOUND_WARNING {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The author of this form has specified the fields which you can fill. Click on any field to start filling form..
        /// </summary>
        internal static string FILLING_FORM_CONTENT {
            get {
                return ResourceManager.GetString("FILLING_FORM_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified fields detected.
        /// </summary>
        internal static string FILLING_FORM_TITLE {
            get {
                return ResourceManager.GetString("FILLING_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your grace period has expired..
        /// </summary>
        internal static string GRACE_EXPRIED_TITLE {
            get {
                return ResourceManager.GetString("GRACE_EXPRIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days remaining in your grace period:.
        /// </summary>
        internal static string GRACE_REMAIN_TITLE {
            get {
                return ResourceManager.GetString("GRACE_REMAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string IDENTIFYKEY_OK {
            get {
                return ResourceManager.GetString("IDENTIFYKEY_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image(s) extracted successfully..
        /// </summary>
        internal static string IMAGE_EXTRACTED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("IMAGE_EXTRACTED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string IMPORT_FILE_PICKER_BUTTON {
            get {
                return ResourceManager.GetString("IMPORT_FILE_PICKER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import File(s).
        /// </summary>
        internal static string IMPORT_FILE_PICKER_TITLE {
            get {
                return ResourceManager.GetString("IMPORT_FILE_PICKER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual size.
        /// </summary>
        internal static string INFO_VIEW_BY_ACTUAL_SIZE {
            get {
                return ResourceManager.GetString("INFO_VIEW_BY_ACTUAL_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size to fit.
        /// </summary>
        internal static string INFO_VIEW_BY_SIZE_TO_FIT {
            get {
                return ResourceManager.GetString("INFO_VIEW_BY_SIZE_TO_FIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PDF is already locked. What do you want to do?.
        /// </summary>
        internal static string INFORMATION_PDF_ALREADY_LOCKED {
            get {
                return ResourceManager.GetString("INFORMATION_PDF_ALREADY_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF has been locked..
        /// </summary>
        internal static string INFORMATION_PDF_HAS_BEEN_LOCKED {
            get {
                return ResourceManager.GetString("INFORMATION_PDF_HAS_BEEN_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF has been unlocked..
        /// </summary>
        internal static string INFORMATION_PDF_HAS_BEEN_UNLOCKED {
            get {
                return ResourceManager.GetString("INFORMATION_PDF_HAS_BEEN_UNLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF is not locked..
        /// </summary>
        internal static string INFORMATION_PDF_IS_NOT_LOCKED {
            get {
                return ResourceManager.GetString("INFORMATION_PDF_IS_NOT_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string INSERT_DROPDESCRIPTION {
            get {
                return ResourceManager.GetString("INSERT_DROPDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop and Start menu shortcuts and File Associations have been disabled by your system administrator..
        /// </summary>
        internal static string INTEGRATION_DISABLE_BY_ADMIN {
            get {
                return ResourceManager.GetString("INTEGRATION_DISABLE_BY_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or sign up.
        /// </summary>
        internal static string LOG_SIGN_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("LOG_SIGN_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged in as:.
        /// </summary>
        internal static string LOGSIGN_SUCESS {
            get {
                return ResourceManager.GetString("LOGSIGN_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No blank pages found..
        /// </summary>
        internal static string NO_BLANK_PAGES_FOUND {
            get {
                return ResourceManager.GetString("NO_BLANK_PAGES_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images to extract..
        /// </summary>
        internal static string NO_IMAGES_EXTRACT_WARNING {
            get {
                return ResourceManager.GetString("NO_IMAGES_EXTRACT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string OPEN_PICKER_BUTTON {
            get {
                return ResourceManager.GetString("OPEN_PICKER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Documents|*.pdf;*.doc*;*.xls*;*.ppt*;*.htm*;*.tex;*.txt;*.rtf;*.xps;*.bmp;*.ccitt;*.dib;*.emf;*.exif;*.gif;*.ico;*.jp*g;*.jfif;*.png;*.tif*;*.wmf|PDF files|*.pdf|Documents|*.doc*;*.xls*;*.ppt*;*.htm*;*.tex;*.txt;*.rtf;*.xps|Images|*.bmp;*.ccitt;*.dib;*.emf;*.exif;*.gif;*.ico;*.jp*g;*.jfif;*.png;*.tif*;*.wmf.
        /// </summary>
        internal static string OPEN_PICKER_FILTERS {
            get {
                return ResourceManager.GetString("OPEN_PICKER_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OPEN_PICKER_TITLE {
            get {
                return ResourceManager.GetString("OPEN_PICKER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page(s) extracted successfully..
        /// </summary>
        internal static string PAGES_EXTRACTED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("PAGES_EXTRACTED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password to open this PDF and the password to change this PDF&apos;s permissions cannot be the same. Please provide a unique password for each..
        /// </summary>
        internal static string PASSWORD_CONSISTENCY_WARNING {
            get {
                return ResourceManager.GetString("PASSWORD_CONSISTENCY_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDF file.
        /// </summary>
        internal static string PDF_FILE {
            get {
                return ResourceManager.GetString("PDF_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file &apos;{0}&apos;. It does not appear to be a valid PDF file..
        /// </summary>
        internal static string PDF_FILE_INVALID_WARNING {
            get {
                return ResourceManager.GetString("PDF_FILE_INVALID_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is read-only and cannot be updated..
        /// </summary>
        internal static string PDF_FILENAME_IS_READ_ONLY {
            get {
                return ResourceManager.GetString("PDF_FILENAME_IS_READ_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF files|*.pdf.
        /// </summary>
        internal static string PDF_FILTER {
            get {
                return ResourceManager.GetString("PDF_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PDF is read-only and cannot be updated..
        /// </summary>
        internal static string PDF_IS_READ_ONLY {
            get {
                return ResourceManager.GetString("PDF_IS_READ_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is locked. You don&apos;t have the permission to do this operation. Please unlock the PDF file first..
        /// </summary>
        internal static string PDF_LOCKED_WARNING {
            get {
                return ResourceManager.GetString("PDF_LOCKED_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current PDF file has been modified. To continue, select one of the options below..
        /// </summary>
        internal static string PDF_MODIFYED_PLEASE_SELECT_ONE_OPTION {
            get {
                return ResourceManager.GetString("PDF_MODIFYED_PLEASE_SELECT_ONE_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDF file &apos;{0}&apos; is protected. Please enter an Open Password to open the file..
        /// </summary>
        internal static string PDF_OPEN_PASSWORD_ACQUIRE {
            get {
                return ResourceManager.GetString("PDF_OPEN_PASSWORD_ACQUIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDF file &apos;{0}&apos; is already protected. Please enter a Permission Password to change the locked permissions..
        /// </summary>
        internal static string PDF_PERMISSION_PASSWORD_ACQUIRE {
            get {
                return ResourceManager.GetString("PDF_PERMISSION_PASSWORD_ACQUIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PDF file has been signed or certified. So you cannot lock/unlock it..
        /// </summary>
        internal static string PDF_SIGNED_OR_CERTIFIED_WARNING {
            get {
                return ResourceManager.GetString("PDF_SIGNED_OR_CERTIFIED_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Express.
        /// </summary>
        internal static string PDF_UTILITY_FRIENDLY_NAME {
            get {
                return ResourceManager.GetString("PDF_UTILITY_FRIENDLY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinZip PDF Express.
        /// </summary>
        internal static string PDF_UTILITY_TITLE {
            get {
                return ResourceManager.GetString("PDF_UTILITY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PdfUtil {
            get {
                object obj = ResourceManager.GetObject("PdfUtil", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected pages ({0} pages).
        /// </summary>
        internal static string PRING_SELECTED_PAGE {
            get {
                return ResourceManager.GetString("PRING_SELECTED_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages ({0} pages).
        /// </summary>
        internal static string PRINT_ALL_PAGES {
            get {
                return ResourceManager.GetString("PRINT_ALL_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current page (page {0}).
        /// </summary>
        internal static string PRINT_CURRENT_PAGE {
            get {
                return ResourceManager.GetString("PRINT_CURRENT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid page number..
        /// </summary>
        internal static string PRINT_INVALID_PAGE_NUMBER {
            get {
                return ResourceManager.GetString("PRINT_INVALID_PAGE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum page number must be less than the maximum page number..
        /// </summary>
        internal static string PRINT_MINIMUMPAGE_LESS_MAXIMUM {
            get {
                return ResourceManager.GetString("PRINT_MINIMUMPAGE_LESS_MAXIMUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page number exceeds the maximum page number ({0})..
        /// </summary>
        internal static string PRINT_PAGE_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("PRINT_PAGE_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RENAME_BOOKMARK_TITLE {
            get {
                return ResourceManager.GetString("RENAME_BOOKMARK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file as {0} ....
        /// </summary>
        internal static string SAVE_AS_PROGRESS_TEXT_CONTENT {
            get {
                return ResourceManager.GetString("SAVE_AS_PROGRESS_TEXT_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes that you have made?.
        /// </summary>
        internal static string SAVE_CHANGES_WARNING {
            get {
                return ResourceManager.GetString("SAVE_CHANGES_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string SAVE_PICKER_BUTTON {
            get {
                return ResourceManager.GetString("SAVE_PICKER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF files|*.pdf|Document|*.doc;*.docx|Images|*.bmp;*.jpg;*.png;*.tif|Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string SAVE_PICKER_FILTERS {
            get {
                return ResourceManager.GetString("SAVE_PICKER_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to PC or Cloud.
        /// </summary>
        internal static string SAVE_PICKER_TITLE {
            get {
                return ResourceManager.GetString("SAVE_PICKER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just close this window.
        /// </summary>
        internal static string SCAN_CLOSE_DESC {
            get {
                return ResourceManager.GetString("SCAN_CLOSE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string SCAN_CLOSE_TITLE {
            get {
                return ResourceManager.GetString("SCAN_CLOSE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the scanned document in WinZip PDF Express.
        /// </summary>
        internal static string SCAN_OPEN_IN_EXPRESS_DESC {
            get {
                return ResourceManager.GetString("SCAN_OPEN_IN_EXPRESS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in WinZip PDF Express.
        /// </summary>
        internal static string SCAN_OPEN_IN_EXPRESS_TITLE {
            get {
                return ResourceManager.GetString("SCAN_OPEN_IN_EXPRESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        internal static string SCAN_SAVE_TO_PATH_CONTENT {
            get {
                return ResourceManager.GetString("SCAN_SAVE_TO_PATH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your scan has been saved as &quot;{0}&quot;..
        /// </summary>
        internal static string SCAN_SAVE_TO_PATH_MAIN {
            get {
                return ResourceManager.GetString("SCAN_SAVE_TO_PATH_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search completed..
        /// </summary>
        internal static string SEARCHING_COMPLETED {
            get {
                return ResourceManager.GetString("SEARCHING_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search completed. No match found..
        /// </summary>
        internal static string SEARCHING_NOT_FOUND {
            get {
                return ResourceManager.GetString("SEARCHING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching page {0}/{1}.
        /// </summary>
        internal static string SEARCHING_PAGE_IN_PROGRESS {
            get {
                return ResourceManager.GetString("SEARCHING_PAGE_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the options below..
        /// </summary>
        internal static string SELECT_ONE_OPTION {
            get {
                return ResourceManager.GetString("SELECT_ONE_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more pages to extract images..
        /// </summary>
        internal static string SELECT_PAGE_TO_EXTRACT_IMAGE_WARNING {
            get {
                return ResourceManager.GetString("SELECT_PAGE_TO_EXTRACT_IMAGE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more pages to extract..
        /// </summary>
        internal static string SELECT_PAGE_TO_EXTRACT_WARNING {
            get {
                return ResourceManager.GetString("SELECT_PAGE_TO_EXTRACT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the page(s) to move..
        /// </summary>
        internal static string SELECT_PAGES_MOVE_WARNING {
            get {
                return ResourceManager.GetString("SELECT_PAGES_MOVE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the page(s) to delete..
        /// </summary>
        internal static string SELECT_PAGES_WARNING {
            get {
                return ResourceManager.GetString("SELECT_PAGES_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select Folder.
        /// </summary>
        internal static string SELECTFOLDER_PICKER_BUTTON {
            get {
                return ResourceManager.GetString("SELECTFOLDER_PICKER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string SELECTFOLDER_PICKER_TITLE {
            get {
                return ResourceManager.GetString("SELECTFOLDER_PICKER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share selected files.
        /// </summary>
        internal static string SHARE_CHARMS_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHARE_CHARMS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for subscribing!.
        /// </summary>
        internal static string SUBSCRIBE_SUCESS {
            get {
                return ResourceManager.GetString("SUBSCRIBE_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this for all files.
        /// </summary>
        internal static string TASKDLG_DO_FOR_ALL_FILE {
            get {
                return ResourceManager.GetString("TASKDLG_DO_FOR_ALL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has expired.
        /// </summary>
        internal static string TRIAL_EXPRIED_CONTENT {
            get {
                return ResourceManager.GetString("TRIAL_EXPRIED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial period.
        /// </summary>
        internal static string TRIAL_EXPRIED_TITLE {
            get {
                return ResourceManager.GetString("TRIAL_EXPRIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days..
        /// </summary>
        internal static string TRIAL_REMAIN_DAYS {
            get {
                return ResourceManager.GetString("TRIAL_REMAIN_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days remaining in your free trial:.
        /// </summary>
        internal static string TRIAL_REMAIN_TITLE {
            get {
                return ResourceManager.GetString("TRIAL_REMAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied..
        /// </summary>
        internal static string WARNING_ACCESS_DENY {
            get {
                return ResourceManager.GetString("WARNING_ACCESS_DENY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password cannot be empty. Please enter the password..
        /// </summary>
        internal static string WARNING_ENCRYPT_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("WARNING_ENCRYPT_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords you typed do not match. Please enter the password again..
        /// </summary>
        internal static string WARNING_ENCRYPT_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("WARNING_ENCRYPT_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all PDF products support/enforce the permissions you have set. Such tools may bypass some or all of this PDF&apos;s permissions..
        /// </summary>
        internal static string WARNING_LOCK_PDF_WARNING {
            get {
                return ResourceManager.GetString("WARNING_LOCK_PDF_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No opened PDF. Please import pages or open a PDF..
        /// </summary>
        internal static string WARNING_NO_OPEN_PDF {
            get {
                return ResourceManager.GetString("WARNING_NO_OPEN_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to save. No opened PDF. Please import pages or open a PDF..
        /// </summary>
        internal static string WARNING_NO_OPEN_PDF_SAVE {
            get {
                return ResourceManager.GetString("WARNING_NO_OPEN_PDF_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no page numbered &apos;{0}&apos; in this document..
        /// </summary>
        internal static string WARNING_NO_PAGE_NUMBER {
            get {
                return ResourceManager.GetString("WARNING_NO_PAGE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PDF is encrypted with an encryption method not supported by WinZip PDF Express.  Unable to unlock this PDF..
        /// </summary>
        internal static string WARNING_NOT_SUPPORTED_ENCRYPTION {
            get {
                return ResourceManager.GetString("WARNING_NOT_SUPPORTED_ENCRYPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Password is empty. Please either deselect the &apos;Password required to open this PDF&apos; option or enter the Open Password..
        /// </summary>
        internal static string WARNING_OPEN_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("WARNING_OPEN_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords you typed do not match. Please enter Open Password again..
        /// </summary>
        internal static string WARNING_OPEN_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("WARNING_OPEN_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.  Extracting pages to the current Zip file may overwrite files that you already have in your Zip file.  Continue with extract?.
        /// </summary>
        internal static string WARNING_OVERWRITE_ZIP_FILE {
            get {
                return ResourceManager.GetString("WARNING_OVERWRITE_ZIP_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect..
        /// </summary>
        internal static string WARNING_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("WARNING_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path, file name, or both are too long..
        /// </summary>
        internal static string WARNING_PATH_TOO_LONG {
            get {
                return ResourceManager.GetString("WARNING_PATH_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDF is empty.  Please import pages or open a PDF..
        /// </summary>
        internal static string WARNING_PDF_IS_EMPTY {
            get {
                return ResourceManager.GetString("WARNING_PDF_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Permissions password is empty. Please either deselect the &apos;Password required to change permissions below&apos; option or enter the Change Permissions password..
        /// </summary>
        internal static string WARNING_PERMISSION_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("WARNING_PERMISSION_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords you typed do not match. Please enter Change Permissions password again..
        /// </summary>
        internal static string WARNING_PERMISSION_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("WARNING_PERMISSION_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your administrator has restricted the use of this feature..
        /// </summary>
        internal static string WARNING_RESTRICTED_FEATURE {
            get {
                return ResourceManager.GetString("WARNING_RESTRICTED_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t save here. Please choose another location..
        /// </summary>
        internal static string WARNING_SAVE_LOCATION_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("WARNING_SAVE_LOCATION_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to lock this PDF file..
        /// </summary>
        internal static string WARNING_UNABLE_TO_LOCK_THIS_PDF {
            get {
                return ResourceManager.GetString("WARNING_UNABLE_TO_LOCK_THIS_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unlock the PDF with the password you provided..
        /// </summary>
        internal static string WARNING_UNABLE_TO_UNLOCK_PDF {
            get {
                return ResourceManager.GetString("WARNING_UNABLE_TO_UNLOCK_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unlock this PDF file..
        /// </summary>
        internal static string WARNING_UNABLE_TO_UNLOCK_THIS_PDF {
            get {
                return ResourceManager.GetString("WARNING_UNABLE_TO_UNLOCK_THIS_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Watermark text..
        /// </summary>
        internal static string WARNING_WATERMARK_NO_CONTENT {
            get {
                return ResourceManager.GetString("WARNING_WATERMARK_NO_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the watermark image..
        /// </summary>
        internal static string WARNING_WATERMARK_NO_IMAGE {
            get {
                return ResourceManager.GetString("WARNING_WATERMARK_NO_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.bmp;*.jpg;*.jpeg;*.png;*.tif.
        /// </summary>
        internal static string WATERMARK_FILTERS {
            get {
                return ResourceManager.GetString("WATERMARK_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential, do not copy.
        /// </summary>
        internal static string WATERMARK_SETTING_DEFAULT_CONTENT {
            get {
                return ResourceManager.GetString("WATERMARK_SETTING_DEFAULT_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinZip.
        /// </summary>
        internal static string WINZIP_TITLE {
            get {
                return ResourceManager.GetString("WINZIP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Save.
        /// </summary>
        internal static string WINZIP_UNSAVE_CHECK_DO_NOT_SAVE {
            get {
                return ResourceManager.GetString("WINZIP_UNSAVE_CHECK_DO_NOT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes will be lost..
        /// </summary>
        internal static string WINZIP_UNSAVE_CHECK_DO_NOT_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("WINZIP_UNSAVE_CHECK_DO_NOT_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string WINZIP_UNSAVE_CHECK_SAVE {
            get {
                return ResourceManager.GetString("WINZIP_UNSAVE_CHECK_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string WINZIP_UNSAVE_CHECK_SAVE_AS {
            get {
                return ResourceManager.GetString("WINZIP_UNSAVE_CHECK_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your changes to another location or file name..
        /// </summary>
        internal static string WINZIP_UNSAVE_CHECK_SAVE_AS_CHANGES {
            get {
                return ResourceManager.GetString("WINZIP_UNSAVE_CHECK_SAVE_AS_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your changes in the current PDF file..
        /// </summary>
        internal static string WINZIP_UNSAVE_CHECK_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("WINZIP_UNSAVE_CHECK_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string ZIP_FILTERS {
            get {
                return ResourceManager.GetString("ZIP_FILTERS", resourceCulture);
            }
        }
    }
}
