//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DupFF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DupFF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string BGT_BUSY {
            get {
                return ResourceManager.GetString("BGT_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string BGT_COMPLETE {
            get {
                return ResourceManager.GetString("BGT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string BGT_DEL_PENDING {
            get {
                return ResourceManager.GetString("BGT_DEL_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule modified externally - use Task Scheduler.
        /// </summary>
        public static string BGT_EXT_SCHED {
            get {
                return ResourceManager.GetString("BGT_EXT_SCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to run.
        /// </summary>
        public static string BGT_READY_TO_RUN {
            get {
                return ResourceManager.GetString("BGT_READY_TO_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now.
        /// </summary>
        public static string BUY_NOW_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("BUY_NOW_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked16 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked20 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked24 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked32 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked40 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked48 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked64 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxChecked80 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxChecked80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked16 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked20 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked24 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked32 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked40 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked48 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked64 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckBoxUnchecked80 {
            get {
                object obj = ResourceManager.GetObject("CheckBoxUnchecked80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string DISMISS_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("DISMISS_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Duplicate File Finder result that is awaiting user action..
        /// </summary>
        public static string ERROR_SELECT_ONE_DFF_ACTION {
            get {
                return ResourceManager.GetString("ERROR_SELECT_ONE_DFF_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one Duplicate File Finder, not pending deletion, to delete..
        /// </summary>
        public static string ERROR_SELECT_ONE_DFF_DELETE {
            get {
                return ResourceManager.GetString("ERROR_SELECT_ONE_DFF_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one Duplicate File Finder result to dismiss.  Dismissing a result will cause the result to be discarded..
        /// </summary>
        public static string ERROR_SELECT_ONE_DFF_DISMISS {
            get {
                return ResourceManager.GetString("ERROR_SELECT_ONE_DFF_DISMISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Duplicate File Finder result must be present in the Results List to Dismiss All results.  Dismissing results will cause the results to be discarded..
        /// </summary>
        public static string ERROR_SELECT_ONE_DFF_DISMISSALL {
            get {
                return ResourceManager.GetString("ERROR_SELECT_ONE_DFF_DISMISSALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Duplicate File Finder, not pending deletion, to modify..
        /// </summary>
        public static string ERROR_SELECT_ONE_DFF_MODIFY {
            get {
                return ResourceManager.GetString("ERROR_SELECT_ONE_DFF_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at one least Duplicate File Finder, not pending deletion, to run..
        /// </summary>
        public static string ERROR_SELECT_ONE_DFF_RUN {
            get {
                return ResourceManager.GetString("ERROR_SELECT_ONE_DFF_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one Duplicate File Finder pending deletion to Undo..
        /// </summary>
        public static string ERROR_SELECT_ONE_DFF_UNDO {
            get {
                return ResourceManager.GetString("ERROR_SELECT_ONE_DFF_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your grace period has expired..
        /// </summary>
        public static string GRACE_EXPRIED_TITLE {
            get {
                return ResourceManager.GetString("GRACE_EXPRIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days remaining in your grace period:.
        /// </summary>
        public static string GRACE_REMAIN_TITLE {
            get {
                return ResourceManager.GetString("GRACE_REMAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or sign up.
        /// </summary>
        public static string LOG_SIGN_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("LOG_SIGN_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged in as:.
        /// </summary>
        public static string LOGSIGN_SUCESS {
            get {
                return ResourceManager.GetString("LOGSIGN_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} duplicates.
        /// </summary>
        public static string RESULT_ACTION_NEEDED {
            get {
                return ResourceManager.GetString("RESULT_ACTION_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See results &gt;&gt;.
        /// </summary>
        public static string SEE_RESULTS {
            get {
                return ResourceManager.GetString("SEE_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for subscribing!.
        /// </summary>
        public static string SUBSCRIBE_SUCESS {
            get {
                return ResourceManager.GetString("SUBSCRIBE_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has expired.
        /// </summary>
        public static string TRIAL_EXPRIED_CONTENT {
            get {
                return ResourceManager.GetString("TRIAL_EXPRIED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your WinZip trial has expired..
        /// </summary>
        public static string TRIAL_EXPRIED_TITLE {
            get {
                return ResourceManager.GetString("TRIAL_EXPRIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string TRIAL_REMAIN_DAYS {
            get {
                return ResourceManager.GetString("TRIAL_REMAIN_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days remaining in your free trial:.
        /// </summary>
        public static string TRIAL_REMAIN_TITLE {
            get {
                return ResourceManager.GetString("TRIAL_REMAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your administrator has restricted the use of this feature..
        /// </summary>
        public static string WARNING_RESTRICTED_FEATURE {
            get {
                return ResourceManager.GetString("WARNING_RESTRICTED_FEATURE", resourceCulture);
            }
        }
    }
}
