//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeShare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SafeShare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this name already exists. Please choose a different name..
        /// </summary>
        internal static string ACCOUNT_NAME_CONFLICT {
            get {
                return ResourceManager.GetString("ACCOUNT_NAME_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add an account to share..
        /// </summary>
        internal static string ACCOUNT_NEEDED {
            get {
                return ResourceManager.GetString("ACCOUNT_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinZip®SafeShare.
        /// </summary>
        internal static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now.
        /// </summary>
        internal static string BUY_NOW_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("BUY_NOW_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your administrator has restricted the use of cloud services..
        /// </summary>
        internal static string CLOUDSERVICE_DISABLED_INFO {
            get {
                return ResourceManager.GetString("CLOUDSERVICE_DISABLED_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine into One PDF Settings.
        /// </summary>
        internal static string COMBINE_INTO_ONE_PDF_SETTING {
            get {
                return ResourceManager.GetString("COMBINE_INTO_ONE_PDF_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to combine {0} {1} into a new PDF..
        /// </summary>
        internal static string COMBINE_PDF_SUMMARY_TEXT {
            get {
                return ResourceManager.GetString("COMBINE_PDF_SUMMARY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine files into one PDF.
        /// </summary>
        internal static string CONVERSION_COMBINE_PDF_NAME {
            get {
                return ResourceManager.GetString("CONVERSION_COMBINE_PDF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to PDF.
        /// </summary>
        internal static string CONVERSION_CONVERT_TO_PDF_NAME {
            get {
                return ResourceManager.GetString("CONVERSION_CONVERT_TO_PDF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Photos.
        /// </summary>
        internal static string CONVERSION_REDUCE_PHOTO_NAME {
            get {
                return ResourceManager.GetString("CONVERSION_REDUCE_PHOTO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Personal Data.
        /// </summary>
        internal static string CONVERSION_REMOVE_PERSONAL_DATA_NAME {
            get {
                return ResourceManager.GetString("CONVERSION_REMOVE_PERSONAL_DATA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark.
        /// </summary>
        internal static string CONVERSION_WATERMARK_NAME {
            get {
                return ResourceManager.GetString("CONVERSION_WATERMARK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to PDF Settings.
        /// </summary>
        internal static string CONVERT_TO_PDF_SETTING {
            get {
                return ResourceManager.GetString("CONVERT_TO_PDF_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to convert {0} {1} to PDFs..
        /// </summary>
        internal static string D2P_SUMMARY_PDFS_TEXT {
            get {
                return ResourceManager.GetString("D2P_SUMMARY_PDFS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to convert {0} {1} to PDF..
        /// </summary>
        internal static string D2P_SUMMARY_TEXT {
            get {
                return ResourceManager.GetString("D2P_SUMMARY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files from the cloud in {0} day(s).
        /// </summary>
        internal static string DELETE_FILE_IN {
            get {
                return ResourceManager.GetString("DELETE_FILE_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string DISMISS_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("DISMISS_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DONE_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("DONE_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body, table, td, a { -webkit-text-size-adj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body, table, td, a { -webkit-text-size-adj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_e {
            get {
                return ResourceManager.GetString("email_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password cannot be empty..
        /// </summary>
        internal static string ERROR_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords you typed do not match..
        /// </summary>
        internal static string ERROR_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet the password policy..
        /// </summary>
        internal static string ERROR_PASSWORD_NOT_MEET_POLICY {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_NOT MEET_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters long..
        /// </summary>
        internal static string ERROR_PASSWORD_TOO_SHORT {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to create a new Zip file on a disk that is read-only: &quot;{0}&quot;..
        /// </summary>
        internal static string FILE_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("FILE_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name cannot be empty..
        /// </summary>
        internal static string FILE_NAME_EMPTY {
            get {
                return ResourceManager.GetString("FILE_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name too long..
        /// </summary>
        internal static string FILE_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("FILE_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string FILE_TEXT {
            get {
                return ResourceManager.GetString("FILE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        internal static string FILES_TEXT {
            get {
                return ResourceManager.GetString("FILES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your grace period has expired..
        /// </summary>
        internal static string GRACE_EXPRIED_TITLE {
            get {
                return ResourceManager.GetString("GRACE_EXPRIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days remaining in your grace period:.
        /// </summary>
        internal static string GRACE_REMAIN_TITLE {
            get {
                return ResourceManager.GetString("GRACE_REMAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file name cannot contain any of the following characters:
        ///      \/:*?&quot;&lt;&gt;|.
        /// </summary>
        internal static string ILLEGAL_CHAR_MSG {
            get {
                return ResourceManager.GetString("ILLEGAL_CHAR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close SafeShare?.
        /// </summary>
        internal static string INFO_APPLICATION_CLOSE {
            get {
                return ResourceManager.GetString("INFO_APPLICATION_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or sign up.
        /// </summary>
        internal static string LOG_SIGN_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("LOG_SIGN_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged in as:.
        /// </summary>
        internal static string LOGSIGN_SUCESS {
            get {
                return ResourceManager.GetString("LOGSIGN_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        internal static string NORMAL_EXPERIENCE_STATE_FAILED_TEXT {
            get {
                return ResourceManager.GetString("NORMAL_EXPERIENCE_STATE_FAILED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re all set..
        /// </summary>
        internal static string NORMAL_EXPERIENCE_STATE_SUCCESS_TEXT {
            get {
                return ResourceManager.GetString("NORMAL_EXPERIENCE_STATE_SUCCESS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One moment please..
        /// </summary>
        internal static string NORMAL_EXPERIENCE_STATE_TEXT {
            get {
                return ResourceManager.GetString("NORMAL_EXPERIENCE_STATE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files|*.*|Office Files|*.doc*;*.dot*;*.wp*;*.rtf;*.pdf;*.xps;*.txt;*.od*;*.xls*;*.qpw;*.wb3;*.xlr;*.ppt*;*.pps*;*.pub;*.shw|Documents|*.doc*;*.dot*;*.wp*;*.rtf;*.pdf;*.xps;*.txt;*.odt|Spreadsheets|*.xls*;*.qpw;*.wb3;*.xlr;*.ods|Presentations|*.ppt*;*.pps*;*.pub;*.wpg;*.shw;*.odp|Pictures|*.jpg;*.jpeg;*.bmp;*.png;*.gif;*.dib;*.tif*;*.psd,*.psp;*.dng|Videos|*.mpg;*.mpeg;*.wmv;*.avi;*.mp4;*.mov*;*.qt;*.flv;*.divx;*.m4v;*.asf;*.3g*|Music|*.mp3;*.mp2;*.wav;*.wma;*.m4*;*.aac,*.rm*,*.ra*;*.aif*;*.ogg|Websites  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OPEN_PICKER_FILTERS {
            get {
                return ResourceManager.GetString("OPEN_PICKER_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        internal static string PASSWORD_COPIED_TEXT {
            get {
                return ResourceManager.GetString("PASSWORD_COPIED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy.
        /// </summary>
        internal static string PASSWORD_COPY_TEXT {
            get {
                return ResourceManager.GetString("PASSWORD_COPY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom password: {0}.
        /// </summary>
        internal static string PASSWORD_CUSTOM_TEXT {
            get {
                return ResourceManager.GetString("PASSWORD_CUSTOM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: {0}.
        /// </summary>
        internal static string PASSWORD_TEXT {
            get {
                return ResourceManager.GetString("PASSWORD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF files|*.pdf.
        /// </summary>
        internal static string PDF_FILTER {
            get {
                return ResourceManager.GetString("PDF_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinZip: over 1 billion downloads..
        /// </summary>
        internal static string PROMOTIONAL_TEXT1 {
            get {
                return ResourceManager.GetString("PROMOTIONAL_TEXT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted by Governments and Enterprises worldwide..
        /// </summary>
        internal static string PROMOTIONAL_TEXT2 {
            get {
                return ResourceManager.GetString("PROMOTIONAL_TEXT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted by Fortune 500 companies worldwide..
        /// </summary>
        internal static string PROMOTIONAL_TEXT3 {
            get {
                return ResourceManager.GetString("PROMOTIONAL_TEXT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted by over 100 thousand companies worldwide..
        /// </summary>
        internal static string PROMOTIONAL_TEXT4 {
            get {
                return ResourceManager.GetString("PROMOTIONAL_TEXT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinZip: managing important files for over 32 years..
        /// </summary>
        internal static string PROMOTIONAL_TEXT5 {
            get {
                return ResourceManager.GetString("PROMOTIONAL_TEXT5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure file sharing made simple..
        /// </summary>
        internal static string PROMOTIONAL_TEXT6 {
            get {
                return ResourceManager.GetString("PROMOTIONAL_TEXT6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to reduce {0} {1} to the selected size. Photos will retain the original aspect ratio..
        /// </summary>
        internal static string REDUCE_IMAGE_SUMMARY_TEXT {
            get {
                return ResourceManager.GetString("REDUCE_IMAGE_SUMMARY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Photos Settings.
        /// </summary>
        internal static string REDUCE_PHOTOS_SETTING {
            get {
                return ResourceManager.GetString("REDUCE_PHOTOS_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Personal Data Settings.
        /// </summary>
        internal static string REMOVE_PERSONAL_DATA_SETTING {
            get {
                return ResourceManager.GetString("REMOVE_PERSONAL_DATA_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one required field is empty. Please check and try again..
        /// </summary>
        internal static string REQUIRED_FIELD_EMPTY {
            get {
                return ResourceManager.GetString("REQUIRED_FIELD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to remove all personal data from {0} {1}..
        /// </summary>
        internal static string RMPD_SUMMARY_TEXT {
            get {
                return ResourceManager.GetString("RMPD_SUMMARY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF files|*.pdf|Document|*.doc;*.docx|Images|*.bmp;*.jpg;*.png;*.tif|Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string SAVE_PICKER_FILTERS {
            get {
                return ResourceManager.GetString("SAVE_PICKER_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SELECT_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("SELECT_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Files.
        /// </summary>
        internal static string SELECT_FILES {
            get {
                return ResourceManager.GetString("SELECT_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string SELECTFOLDER_PICKER_BUTTON {
            get {
                return ResourceManager.GetString("SELECTFOLDER_PICKER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string SELECTFOLDER_PICKER_TITLE {
            get {
                return ResourceManager.GetString("SELECTFOLDER_PICKER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a service with the name you specified..
        /// </summary>
        internal static string SERVICE_NAME_CONFLICT {
            get {
                return ResourceManager.GetString("SERVICE_NAME_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}% reduction).
        /// </summary>
        internal static string SIZE_REDUCTION_TEXT {
            get {
                return ResourceManager.GetString("SIZE_REDUCTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string SKIP_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("SKIP_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SUBMIT_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("SUBMIT_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for subscribing!.
        /// </summary>
        internal static string SUBSCRIBE_SUCESS {
            get {
                return ResourceManager.GetString("SUBSCRIBE_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        internal static string SURVEY_BACK_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("SURVEY_BACK_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string SURVEY_DEFAULT_OP_OTHER {
            get {
                return ResourceManager.GetString("SURVEY_DEFAULT_OP_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email setup.
        /// </summary>
        internal static string SURVEY_DEFAULT_OP1 {
            get {
                return ResourceManager.GetString("SURVEY_DEFAULT_OP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud setup.
        /// </summary>
        internal static string SURVEY_DEFAULT_OP2 {
            get {
                return ResourceManager.GetString("SURVEY_DEFAULT_OP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption setup &amp; Sharing.
        /// </summary>
        internal static string SURVEY_DEFAULT_OP3 {
            get {
                return ResourceManager.GetString("SURVEY_DEFAULT_OP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Conversions.
        /// </summary>
        internal static string SURVEY_DEFAULT_OP4 {
            get {
                return ResourceManager.GetString("SURVEY_DEFAULT_OP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How was your experience?.
        /// </summary>
        internal static string SURVEY_DEFAULT_REVIEW_HEADER {
            get {
                return ResourceManager.GetString("SURVEY_DEFAULT_REVIEW_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can we improve?.
        /// </summary>
        internal static string SURVEY_DEFAULT_SURVEY_HEADER {
            get {
                return ResourceManager.GetString("SURVEY_DEFAULT_SURVEY_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip survey &gt;.
        /// </summary>
        internal static string SURVEY_SKIP_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("SURVEY_SKIP_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        internal static string TEXT_ADD_ACCOUNT {
            get {
                return ResourceManager.GetString("TEXT_ADD_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new service.
        /// </summary>
        internal static string TEXT_ADD_NEW_SERVICE {
            get {
                return ResourceManager.GetString("TEXT_ADD_NEW_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Setup.
        /// </summary>
        internal static string TEXT_ADVANCED_SETUP {
            get {
                return ResourceManager.GetString("TEXT_ADVANCED_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        internal static string TEXT_SYSTEM_SETTINGS {
            get {
                return ResourceManager.GetString("TEXT_SYSTEM_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Own Program.
        /// </summary>
        internal static string TEXT_USERS_OWN_PROGRAM {
            get {
                return ResourceManager.GetString("TEXT_USERS_OWN_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account for free or log in.
        /// </summary>
        internal static string TEXT_ZIPSHARE_EMPTY_ACCOUNT {
            get {
                return ResourceManager.GetString("TEXT_ZIPSHARE_EMPTY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} items).
        /// </summary>
        internal static string TOTAL_ITEM_COUNT {
            get {
                return ResourceManager.GetString("TOTAL_ITEM_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} item).
        /// </summary>
        internal static string TOTAL_ITEM_COUNT1 {
            get {
                return ResourceManager.GetString("TOTAL_ITEM_COUNT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total unzipped size: {0} {1}.
        /// </summary>
        internal static string TOTAL_UNZIP_SIZE {
            get {
                return ResourceManager.GetString("TOTAL_UNZIP_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has expired.
        /// </summary>
        internal static string TRIAL_EXPRIED_CONTENT {
            get {
                return ResourceManager.GetString("TRIAL_EXPRIED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your WinZip trial has expired..
        /// </summary>
        internal static string TRIAL_EXPRIED_TITLE {
            get {
                return ResourceManager.GetString("TRIAL_EXPRIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TRIAL_REMAIN_DAYS {
            get {
                return ResourceManager.GetString("TRIAL_REMAIN_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days remaining in your free trial:.
        /// </summary>
        internal static string TRIAL_REMAIN_TITLE {
            get {
                return ResourceManager.GetString("TRIAL_REMAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark Settings.
        /// </summary>
        internal static string WARKMARK_SETTING {
            get {
                return ResourceManager.GetString("WARKMARK_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied..
        /// </summary>
        internal static string WARNING_ACCESS_DENY {
            get {
                return ResourceManager.GetString("WARNING_ACCESS_DENY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to discard the changes you have made?.
        /// </summary>
        internal static string WARNING_DISCARD_CHANGES {
            get {
                return ResourceManager.GetString("WARNING_DISCARD_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed. The file &quot;{0}&quot; is in use. Please try again later..
        /// </summary>
        internal static string WARNING_FILE_IN_USE {
            get {
                return ResourceManager.GetString("WARNING_FILE_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed. The specified path, file name, or both are too long..
        /// </summary>
        internal static string WARNING_PATH_TOO_LONG {
            get {
                return ResourceManager.GetString("WARNING_PATH_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your administrator has restricted the use of this feature..
        /// </summary>
        internal static string WARNING_RESTRICTED_FEATURE {
            get {
                return ResourceManager.GetString("WARNING_RESTRICTED_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential, do not copy.
        /// </summary>
        internal static string WATERMARK_CONTENT {
            get {
                return ResourceManager.GetString("WATERMARK_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.bmp;*.jpg;*.png;*.tif.
        /// </summary>
        internal static string WATERMARK_FILTERS {
            get {
                return ResourceManager.GetString("WATERMARK_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to watermark {0} {1}..
        /// </summary>
        internal static string WATERMARK_SUMMARY_TEXT {
            get {
                return ResourceManager.GetString("WATERMARK_SUMMARY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipx files|*.zipx|Zip files|*.zip.
        /// </summary>
        internal static string ZIP_FILTERS {
            get {
                return ResourceManager.GetString("ZIP_FILTERS", resourceCulture);
            }
        }
    }
}
