//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeShare.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertOptAddWatermark {
            get {
                return ((bool)(this["ConvertOptAddWatermark"]));
            }
            set {
                this["ConvertOptAddWatermark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int ConvertOptWatermarkAngle {
            get {
                return ((int)(this["ConvertOptWatermarkAngle"]));
            }
            set {
                this["ConvertOptWatermarkAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int ConvertOptWatermarkOpacity {
            get {
                return ((int)(this["ConvertOptWatermarkOpacity"]));
            }
            set {
                this["ConvertOptWatermarkOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertOptWatermarkDateStampIsChecked {
            get {
                return ((bool)(this["ConvertOptWatermarkDateStampIsChecked"]));
            }
            set {
                this["ConvertOptWatermarkDateStampIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertOptWatermarkTimeStampIsChecked {
            get {
                return ((bool)(this["ConvertOptWatermarkTimeStampIsChecked"]));
            }
            set {
                this["ConvertOptWatermarkTimeStampIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConvertOptWatermarkContent {
            get {
                return ((string)(this["ConvertOptWatermarkContent"]));
            }
            set {
                this["ConvertOptWatermarkContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ConvertOptWatermarkTextPosition {
            get {
                return ((int)(this["ConvertOptWatermarkTextPosition"]));
            }
            set {
                this["ConvertOptWatermarkTextPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertOptRemovePersonalData {
            get {
                return ((bool)(this["ConvertOptRemovePersonalData"]));
            }
            set {
                this["ConvertOptRemovePersonalData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertOptFilesToPdf {
            get {
                return ((bool)(this["ConvertOptFilesToPdf"]));
            }
            set {
                this["ConvertOptFilesToPdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertOptRemoveComments {
            get {
                return ((bool)(this["ConvertOptRemoveComments"]));
            }
            set {
                this["ConvertOptRemoveComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertOptRemovemarkup {
            get {
                return ((bool)(this["ConvertOptRemovemarkup"]));
            }
            set {
                this["ConvertOptRemovemarkup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertOptMakePdfReadonly {
            get {
                return ((bool)(this["ConvertOptMakePdfReadonly"]));
            }
            set {
                this["ConvertOptMakePdfReadonly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConvertOptResolution {
            get {
                return ((int)(this["ConvertOptResolution"]));
            }
            set {
                this["ConvertOptResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ConvertOptQuality {
            get {
                return ((int)(this["ConvertOptQuality"]));
            }
            set {
                this["ConvertOptQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertOptCombineIntoOnePdf {
            get {
                return ((bool)(this["ConvertOptCombineIntoOnePdf"]));
            }
            set {
                this["ConvertOptCombineIntoOnePdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertOptDeleteOriginalFiles {
            get {
                return ((bool)(this["ConvertOptDeleteOriginalFiles"]));
            }
            set {
                this["ConvertOptDeleteOriginalFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertOptUseWipeToDeleteFiles {
            get {
                return ((bool)(this["ConvertOptUseWipeToDeleteFiles"]));
            }
            set {
                this["ConvertOptUseWipeToDeleteFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConvertOptReducePhoteResolution {
            get {
                return ((int)(this["ConvertOptReducePhoteResolution"]));
            }
            set {
                this["ConvertOptReducePhoteResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveFilePath {
            get {
                return ((string)(this["SaveFilePath"]));
            }
            set {
                this["SaveFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DeleteFileDays {
            get {
                return ((int)(this["DeleteFileDays"]));
            }
            set {
                this["DeleteFileDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LocalDeviceChecked {
            get {
                return ((bool)(this["LocalDeviceChecked"]));
            }
            set {
                this["LocalDeviceChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomEncryptPassword {
            get {
                return ((string)(this["CustomEncryptPassword"]));
            }
            set {
                this["CustomEncryptPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveCopyChecked {
            get {
                return ((bool)(this["SaveCopyChecked"]));
            }
            set {
                this["SaveCopyChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReducePhotosChecked {
            get {
                return ((bool)(this["ReducePhotosChecked"]));
            }
            set {
                this["ReducePhotosChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteFileChecked {
            get {
                return ((bool)(this["DeleteFileChecked"]));
            }
            set {
                this["DeleteFileChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EmailAttachmentIsChecked {
            get {
                return ((bool)(this["EmailAttachmentIsChecked"]));
            }
            set {
                this["EmailAttachmentIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EmailLinkIsChecked {
            get {
                return ((bool)(this["EmailLinkIsChecked"]));
            }
            set {
                this["EmailLinkIsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EncryptFile {
            get {
                return ((bool)(this["EncryptFile"]));
            }
            set {
                this["EncryptFile"] = value;
            }
        }
    }
}
