name: publish-ci

on:
  pull_request:
    types:
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  GITHUB_PACKAGE_SOURCE: 'https://nuget.pkg.github.com/Alludo-WinZip/index.json'
  CHOCO_PACKAGE_CONFIG_PATH: '.\Tools'
  Tooling_PATH: '.\Tooling'
                                      

jobs:
  publish:
    name: dot net build Windows
    runs-on: windows-latest
    if: github.repository == 'Alludo-WinZip/Applets' && github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get authenticated user and their permissions
        run: |
          $PAT_TOKEN = "${{ secrets.PAT_TOKEN }}"
          $response = Invoke-RestMethod -Uri "https://api.github.com/user" -Headers @{"Authorization"="token $PAT_TOKEN"}
          
          # Extract the user's name
          $githubName = $response.login
          
          # Set the GITHUB_NAME environment variable
          echo "GITHUB_NAME=$githubName" >> $env:GITHUB_ENV

      - name: Check Choco Installed
        shell: powershell
        run: |
          choco --version

      - name: Install .NET Framework 4.6.1
        shell: powershell
        run: |
          mkdir ./Downloads
          Invoke-WebRequest -Uri 'https://download.microsoft.com/download/F/1/D/F1DEB8DB-D277-4EF9-9F48-3A65D4D8F965/NDP461-DevPack-KB3105179-ENU.exe' -OutFile './Downloads/NDP461-KB3102436-x86-x64-AllOS-ENU.exe'
          Start-Process -FilePath './Downloads/NDP461-KB3102436-x86-x64-AllOS-ENU.exe' -ArgumentList '/q' -Wait

      - name: Check NuGet command line tool
        shell: powershell
        run: |
          nuget help | select -First 1; exit 0

      - name: Build Applets
        shell: powershell
        run: |
          $installPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationpath
          Import-Module (Join-Path $installPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
          Enter-VsDevShell -VsInstallPath $installPath -SkipAutomaticLocation -Arch amd64 -HostArch amd64
          msbuild Applets.sln /t:restore,build -p:RestorePackagesConfig=true
          
      - name: Update chocolatey package version in config
        id: choco-package-version-update
        shell: powershell
        run: |
          Import-Module (Resolve-Path("$env:Tooling_PATH\UpdateChocolateyPackageVersion.psm1"))
          UpdateChocolateyPackageVersion -GitHubToken "$env:GITHUB_TOKEN" -SpecFilePath "$env:CHOCO_PACKAGE_CONFIG_PATH"

      - name: Create chocolatey package
        shell: powershell
        run: |
          $nugetSpecFile = (Get-ChildItem -path "$env:CHOCO_PACKAGE_CONFIG_PATH" -Filter *.nuspec | Select-Object -First 1);
          choco pack $nugetSpecFile.FullName --outputdirectory "$env:CHOCO_PACKAGE_CONFIG_PATH"

      - name: Publish
        shell: powershell
        run: |
          nuget setapikey ${env:GITHUB_TOKEN} -Source "github" -ConfigFile NuGet.config
          $NugetPackage = (Get-ChildItem -path "$env:CHOCO_PACKAGE_CONFIG_PATH" -Filter *.nupkg | Select-Object -First 1).fullname
          nuget push $NugetPackage -ConfigFile NuGet.config -source "github" -Force